###
GET http://localhost:8080/notes
Authorization: Bearer {{token}}

###
GET http://localhost:8080/notes/{{noteId}}
Authorization: Bearer {{token}}

###

POST http://localhost:8080/notes
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "note title",
  "note": "note note"
}

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": {{email}},
  "password": {{password}}
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": {{email}},
  "password": {{password}}
}

