###
GET http://localhost:8080/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWt1YmVra296YWsiLCJpYXQiOjE2MTc4MTkyMTEsImV4cCI6MTYxNzgyMjgxMX0.x925jy6NU-VUQGajZ4ocD3sZ_OjZKlt1WbS3GTwwLEQ

###
POST http://localhost:8080/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWt1YmVra296YWsiLCJpYXQiOjE2MTc4MTkyMTEsImV4cCI6MTYxNzgyMjgxMX0.x925jy6NU-VUQGajZ4ocD3sZ_OjZKlt1WbS3GTwwLEQ
Content-Type: application/json

{
  "title": "bleble",
  "note": "dupadupa dupa"
}

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "jakubekkozak",
  "password": "dupadupa"
}

###
POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "username": "jakubekkozak",
  "password": "dupadupa"
}

